### ISSUE TITLE
Add Sprite styling update

### ISSUE THREAD

**Issue by StioStudio** [nikeedev/GameEngine_js#2]
Add so Sprite class could change style (height and width) when it runs either Draw function or Update func.

@nikeedev Fix this! 

P.S. Add to Notion.

**Comment by nikeedev** [comment]
> Hello @StioStudio! Thanks for recommending this feature, and just to let you know it, we are adding!
> 
> To change style of a sprite, do this: `name_of_sprite.style = "width: 200px;"` or something else, and paint.
> 
> This feature will be added in update 0.4.0, so see with the GameEngine.js when the current update says 0.4.0, then the update is out
> 
> _Sincerly, @nikeedev_

BTW @StioStudio, here is link to check when update is 0.4.0: https://nikeedev.github.io/GameEngine_js/.

Also it will show nothing, and thats because in our latest dev updates, some features wont allow website to show the current version, but when you see it, that means that website **_and_** the update are out.
